"""Made invited_by nullable

Revision ID: efa5635a6d82
Revises: 2b8c4757d8f3
Create Date: 2026-03-19 18:27:19.387745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa5635a6d82'
down_revision: Union[str, Sequence[str], None] = '2b8c4757d8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitations', 'invited_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitations', 'invited_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
