"""remove group for invites

Revision ID: 8b36c88896f8
Revises: 2b8c4757d8f3
Create Date: 2026-03-19 20:31:58.441079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b36c88896f8'
down_revision: Union[str, Sequence[str], None] = '2b8c4757d8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_group_id_fkey'), 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invitations_group_id_fkey'), 'invitations', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
